### PR TITLE
Invoice comment feature (WIP)

### PR DESCRIPTION
**Pull request by nspo**

### CODE REVIEW

**Comment by nspo** [comment]
Will fix table alignment

image

**Comment by nspo** [comment]
Now it looks like this:

image

image

image

**Comment by nspo** [comment]
@Merlijnv does this look OK for you?

**Comment by Merlijnv** [comment]
this looks great I think it's complete now @nspo

**Comment by Merlijnv** [comment]
The link seems to be missing in payment reminder @nspo

**Pull request merged**
