### PR TITLE
Negativevaluta

### PR DESCRIPTION
**Pull request by Merlijnv**
Fixed the negative value that isn't displayed correctly in some currencies.
You can now change it so it can be -€1,00 or €1,00 dependant on your liking.

### CODE REVIEW

**Comment by nspo** [comment]
Can you explain in which places you saw these issues and how exactly they appeared? Sounds a bit surprising to me. With `LANGUAGE_CODE = 'de-de'`  I think I get positive currency values like `12,34 €` and negative ones like `-12,34 €` everywhere. Did not notice a minus after a number anywhere yet.

**Comment by Merlijnv** [comment]
Okay so a normal form of valuta in the netherlands is - €10,99 and what I get with NL-nl €10,10- which isn't what I want

**Comment by Merlijnv** [comment]
@nspo I have tried both nl-NL and nl-nl but same results so that doesn't fix the problem

**Comment by nspo** [comment]
So I finally looked into this issue a little bit and it seems to be really weird. A minimal example showing the same behavior you dislike is this:

```
#!/usr/bin/env python3
import locale
from decimal import Decimal

locale.setlocale(locale.LC_ALL, 'nl_NL.UTF-8')
d=Decimal("-1.23")

print(locale.localeconv()["n_sign_posn"])
print(locale.currency(d)) 
```
```
4
€ 1,23-
```

If you look [here](https://docs.python.org/3/library/locale.html) `n_sign_pos == 4` means exactly what's happening, so it looks like exactly this behavior is baked into the language conventions for `nl_NL`. Some more background information can be found [here](http://www.bubblefoundry.com/blog/2013/11/formatting-dutch-currency-amounts/) I think. Though the CLDR standard seems to have changed for the better in the meantime it still has this bad behavior on my test system with Ubuntu 20.04. 

I did not find an obvious/clean way to modify the language conventions in this regard (with only a minimal amount of hacks). This is obviously not a very satisfying answer!  But I found out that the `babel` package seems to have much saner defaults which align with the official Dutch standards:

```
>>> import babel.numbers
>>> print(babel.numbers.format_currency(-12.34, currency='EUR', locale='nl_NL.UTF-8'))
€ -12,34
```

As this also seems to be what the [Nederlandse Taalunie recommends](https://taaladvies.net/taal/advies/vraag/1198), I will integrate this in a branch for you to review. It should lead to a really clean fix :)

**Comment by nspo** [comment]
@Merlijnv Do you want to have a quick look at #26? I also added some screenshots

**Comment by Merlijnv** [comment]
@nspo sorry dit not get any messages in my mail so did not see until now looks amazing, good job!

**Pull request closed without merging**
